<?php

declare(strict_types=1);

namespace LaraGram\Mcp\Telegram\BotApi;

use Closure;
use InvalidArgumentException;
use LaraGram\Laraquest\Schema\ApiSchema;

class Toolset
{
    /**
     * Named groups of method patterns.
     *
     * @var array<string, array<int, string>>
     */
    public const PRESETS = [
        'read' => ['get*'],
        'messaging' => ['send*', 'forward*', 'copy*', 'edit*', 'stopMessageLiveLocation', 'stopPoll', 'deleteMessage', 'deleteMessages', 'setMessageReaction', 'pinChatMessage', 'unpinChatMessage'],
        'moderation' => ['ban*', 'unban*', 'restrict*', 'promote*', 'approveChatJoinRequest', 'declineChatJoinRequest', '*ChatInviteLink', 'setChat*', 'deleteChat*', 'getChat*', 'setChatAdministratorCustomTitle'],
        'forum' => ['*ForumTopic*', '*GeneralForumTopic*'],
        'commands' => ['*MyCommands', '*MyName', '*MyDescription', '*MyShortDescription', '*ChatMenuButton', '*MyDefaultAdministratorRights', 'getMe'],
        'inline' => ['answerInlineQuery', 'answerCallbackQuery', 'answerWebAppQuery', 'savePrepared*'],
        'stickers' => ['*Sticker*'],
        'payments' => ['sendInvoice', 'createInvoiceLink', 'answerShippingQuery', 'answerPreCheckoutQuery', '*Star*', 'refundStarPayment', 'editUserStarSubscription'],
        'business' => ['*Business*'],
        'gifts' => ['*Gift*'],
        'stories' => ['*Story'],
        'games' => ['sendGame', 'setGameScore', 'getGameHighScores'],
        'files' => ['getFile', 'getUserProfilePhotos', 'uploadStickerFile'],
    ];

    /** @var array<int, string> */
    protected array $only = [];

    /** @var array<int, string> */
    protected array $except = [];

    /** @var array<int, string> */
    protected array $dangerous = [];

    protected bool $withoutDestructive = false;

    protected bool $readOnly = false;

    protected ?string $connection = null;

    /** @var array<int, string>|null */
    protected ?array $connections = null;

    protected string $prefix = 'telegram_';

    protected int $depth = 1;

    protected bool $typeLookup = true;

    protected bool $confirmDestructive = false;

    /** @var (Closure(): array<int, int|string>)|array<int, int|string>|null */
    protected Closure|array|null $allowedChats = null;

    protected ?string $abilityFormat = null;

    /** @var array<string, array{description: string, returns: string|null, parameters: array<int, array<string, mixed>>}>|null */
    protected ?array $methods = null;

    /** @var array<string, array{description: string, fields: array<int, array<string, mixed>>}>|null */
    protected ?array $types = null;

    /**
     * Use the given schema instead of the one generated by Laraquest.
     *
     * @param  array{methods: array<string, mixed>, types: array<string, mixed>}  $schema
     */
    public function withSchema(array $schema): static
    {
        $this->methods = $schema['methods'];
        $this->types = $schema['types'];

        return $this;
    }

    /**
     * Only include methods matching the given name patterns (e.g. "send*").
     */
    public function only(string ...$patterns): static
    {
        $this->only = [...$this->only, ...$patterns];

        return $this;
    }

    /**
     * Exclude methods matching the given name patterns.
     */
    public function except(string ...$patterns): static
    {
        $this->except = [...$this->except, ...$patterns];

        return $this;
    }

    /**
     * Only include the methods of the given presets (see Toolset::PRESETS).
     */
    public function preset(string ...$presets): static
    {
        foreach ($presets as $preset) {
            if (! isset(self::PRESETS[$preset])) {
                throw new InvalidArgumentException("Unknown Bot API preset [{$preset}].");
            }

            $this->only(...self::PRESETS[$preset]);
        }

        return $this;
    }

    /**
     * Only include read-only ("get*") methods.
     */
    public function readOnly(): static
    {
        $this->readOnly = true;

        return $this;
    }

    /**
     * Exclude methods that delete, ban, revoke or otherwise irreversibly change state.
     */
    public function withoutDestructive(): static
    {
        $this->withoutDestructive = true;

        return $this;
    }

    /**
     * Allow methods that are excluded by default (see Method::DANGEROUS).
     */
    public function allowDangerous(string ...$methods): static
    {
        $this->dangerous = [...$this->dangerous, ...$methods];

        return $this;
    }

    /**
     * Send every call with the given bot connection.
     */
    public function connection(string $connection): static
    {
        $this->connection = $connection;

        return $this;
    }

    /**
     * Let the client pick one of the given connections (all configured connections by default).
     *
     * @param  array<int, string>|null  $connections
     */
    public function selectableConnections(?array $connections = null): static
    {
        $this->connections = $connections ?? Client::connections();

        return $this;
    }

    /**
     * Set the prefix of the tool names (default "telegram_").
     */
    public function prefix(string $prefix): static
    {
        $this->prefix = $prefix;

        return $this;
    }

    /**
     * Set how deep nested Telegram objects are described in the input schemas.
     */
    public function depth(int $depth): static
    {
        $this->depth = max(0, $depth);

        return $this;
    }

    /**
     * Ask the user to confirm (through elicitation) before a destructive method runs.
     * Clients without elicitation support cannot run destructive methods.
     */
    public function confirmDestructive(): static
    {
        $this->confirmDestructive = true;

        return $this;
    }

    /**
     * Don't add the "describe_type" tool.
     */
    public function withoutTypeLookup(): static
    {
        $this->typeLookup = false;

        return $this;
    }

    /**
     * Restrict "chat_id" arguments to the given chats.
     *
     * @param  (Closure(): array<int, int|string>)|array<int, int|string>  $chats
     */
    public function allowChats(Closure|array $chats): static
    {
        $this->allowedChats = $chats;

        return $this;
    }

    /**
     * Require the access token to grant an ability per method, e.g. "telegram:{method}".
     *
     * The "{method}" placeholder is replaced with the Bot API method name.
     */
    public function requireAbilities(string $format = 'telegram:{method}'): static
    {
        $this->abilityFormat = $format;

        return $this;
    }

    /**
     * Get the matching methods.
     *
     * @return array<int, Method>
     */
    public function methods(): array
    {
        $methods = [];

        foreach ($this->methodDefinitions() as $name => $definition) {
            $method = Method::fromSchema($name, $definition);

            if ($this->includes($method)) {
                $methods[] = $method;
            }
        }

        return $methods;
    }

    /**
     * Get a tool for every matching method, plus the "describe_type" tool.
     *
     * @return array<int, MethodTool|DescribeTypeTool>
     */
    public function all(): array
    {
        $tools = array_map(fn (Method $method): MethodTool => new MethodTool($method, $this), $this->methods());

        if ($this->typeLookup && $tools !== []) {
            $tools[] = new DescribeTypeTool($this);
        }

        return $tools;
    }

    protected function includes(Method $method): bool
    {
        if ($method->isDangerous() && ! in_array($method->name, $this->dangerous, true)) {
            return false;
        }

        if ($this->only !== [] && ! $method->is($this->only)) {
            return false;
        }

        if ($this->except !== [] && $method->is($this->except)) {
            return false;
        }

        if ($this->readOnly && ! $method->isReadOnly()) {
            return false;
        }

        return ! ($this->withoutDestructive && $method->isDestructive());
    }

    /**
     * @internal
     */
    public function confirmsDestructive(): bool
    {
        return $this->confirmDestructive;
    }

    /**
     * @internal
     */
    public function fingerprint(): string
    {
        return md5(serialize([
            $this->prefix,
            $this->depth,
            $this->selectsConnection() ? $this->connections : null,
            ApiSchema::exists() && $this->methods === null ? ApiSchema::version() : spl_object_id($this),
        ]));
    }

    /**
     * @internal
     */
    public function prefixValue(): string
    {
        return $this->prefix;
    }

    /**
     * @internal
     *
     * @return array<string, array{description: string, fields: array<int, array{name: string, type: string, required: bool, description: string}>}>
     */
    public function types(): array
    {
        return $this->types ??= ApiSchema::types();
    }

    /**
     * @internal
     *
     * @return array<string, array{description: string, returns: string|null, parameters: array<int, array{name: string, type: string, required: bool, description: string}>}>
     */
    public function methodDefinitions(): array
    {
        return $this->methods ??= ApiSchema::methods();
    }

    /**
     * @internal
     */
    public function depthValue(): int
    {
        return $this->depth;
    }

    /**
     * @internal
     */
    public function fixedConnection(): ?string
    {
        return $this->connection;
    }

    /**
     * @internal
     */
    public function selectsConnection(): bool
    {
        return $this->connection === null && $this->connections !== null && $this->connections !== [];
    }

    /**
     * @internal
     *
     * @return array<int, string>
     */
    public function connections(): array
    {
        return $this->connections ?? [];
    }

    /**
     * @internal
     */
    public function chatAllowed(mixed $chatId): bool
    {
        if ($this->allowedChats === null) {
            return true;
        }

        $allowed = $this->allowedChats instanceof Closure ? ($this->allowedChats)() : $this->allowedChats;

        return in_array((string) $chatId, array_map('strval', $allowed), true);
    }

    /**
     * @internal
     *
     * @return array<int, string>
     */
    public function abilitiesFor(Method $method): array
    {
        return $this->abilityFormat === null ? [] : [str_replace('{method}', $method->name, $this->abilityFormat)];
    }
}
